# Generated by Django 4.1.6 on 2023-02-13 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rapper',
        ),
    ]
