# Generated by Django 4.1.6 on 2023-02-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_delete_rapper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='../Data/'),
        ),
    ]
