# Generated by Django 4.1.7 on 2023-04-19 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_delete_result_file_date_uploaded_file_res'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='date_uploaded',
        ),
    ]
